---
output:
  html_document:
    highlight: kate
    theme: cosmo
  pdf_document: default
---

```{r setup, echo=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

install.packages("primes")
install.packages("rlist")
library(primes)
library(MASS)
library(rlist)

```

```{r initial_setup}


```

```{r functions}

# Initial setup
max_prime <- 200
primes <- primes::generate_primes(2, max_prime)
p_1 <- primes[1]

# First elasticities
u_1 <- list(1)
u_2 <- list(2)
u_3 <- 3:4
u_4 <- 3:5
elasticities <- list(u_1, u_2, u_3, u_4)

# Min element in U_k
min_elast <- function(k){
  return (ceiling(k*(p_1 - 1)/p_1))
}

# Max element in U_k
max_elast <- function(k){
  return (floor(k*p_1/(p_1 - 1)))
}

# Testing
#min_elast(5)
#max_elast(5)

add_known_elasticities_from_previous_sets <- function(k) {
  #k <- 5
  u_k <- list()
  for(i in 1:length(elasticities)){
    #i = 3
    diff <- k - i
    if(diff <= 0)
    {
      print("The value of k must be smaller than that of i")
      break
    }
    u <- unlist(elasticities[i])
    if(length(u) != 1){
      for(j in 1:length(u)){
        #j <- 2
        if(u[j] != i){
          if(!((u[j] + diff) %in% u_k))
            u_k[length(u_k) + 1] <- u[j] + diff
          
          if(u[j] <= k && !((i + diff) %in% u_k)){
            u_k[length(u_k) + 1] <- i + diff
          }
        }
      }
    }
  }
  return(unique(u_k))
}

# Testing
#u_5 <- add_known_elasticities_from_previous_sets(5)

max_atom_index_to_consider <- function(k, n){
  #k <- 5
  #n <- 4
  for(i in 1:n){
    #i <- 4
    if((primes[i] - 1) >= n){
      return(i)
    }
  }
  print("It didnt find the max_atom_to_consider.")
}


# The list atoms contains only the numerators of atoms
length_of_n_as_the_sum_of_elements_in_list_rec <- function(n, max_atom_index_to_consider, sum, total_summands){
  if(n == sum) return (c(total_summands))
  if(sum > n) return (c(NA))
  result <- list()
  for(i in 1:max_atom_index_to_consider){
    temp <- length_of_n_as_the_sum_of_elements_in_list_rec(n, max_atom_index_to_consider, sum + primes[i] - 1, total_summands + primes[i])
    result[[length(result) + 1]] <- temp
  }
  return (result)
}


# atoms is a list containing only the numerators and 
# is assumed to be a strictly increasing list of integers
length_of_n_as_the_sum_of_elements_in_list <- function(n, max_atom_index_to_consider){
  if(max_atom_index_to_consider == 0) return (c(NA))
  if(n < (primes[1] - 1)) return (c(NA))
  
  res <- unlist(length_of_n_as_the_sum_of_elements_in_list_rec(n, max_atom_index_to_consider, 0, 0))
  res <- unique(res[!is.na(res)])
  
  return (res)
}

# Testing
#res <- length_of_n_as_the_sum_of_elements_in_list_rec(4, c(1, 2, 4), 0, 0)
#res <- length_of_n_as_the_sum_of_elements_in_list(4, c(1, 2, 4))

add_new_elasticities <- function(k){
  #k <- 5
  #n <- 4
  u_k <- list()
  #possible_elast <- setdiff(min_elast(k):max_elast(k), add_known_elasticities_from_previous_sets(k))
  max_integer <- k - 1
  min_integer <- ceiling(k/2)
  # Each atom must be multiplied by their denominator (check this)
  for(n in min_integer:max_integer){
    max_atom_index_to_consider <- max_atom_index_to_consider(k, n)
    u_k <- c(u_k, setdiff(length_of_n_as_the_sum_of_elements_in_list(n, max_atom_index_to_consider), u_k))
  }
  return (u_k)
}

find_u_k <- function(k){
  u_k <- unique(unlist(c(add_known_elasticities_from_previous_sets(k), add_new_elasticities(k))))
  return (sort(u_k))
}


min_k <- 5
max_k <- 10
for(i in min_k:max_k){
  elasticities[[i]] <- find_u_k(i)
}


```


``` {r crazy_testing}

z <- 1:5
c <- c(1, 5, 10)
setdiff(z, c)
setdiff(c, z)
str(z)
c <- z[!(z %in% c(2, 3))]
c

temp <- list()
other <- list(2, 3, 4)
temp[[1]] <- other
temp[[2]] <- c(other, 100)
unlist(temp)


sort(c(4,3))

```