---
title: "Print & Graph U_k"
author: "Marly Cormar"
date: "7/22/2018"
output:
  html_document:
    highlight: kate
    theme: cosmo
  pdf_document: default
---


```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

```


```{r install_packages, echo=FALSE, warning=FALSE, include=FALSE}

install.packages("kableExtra", repos = "http://cran.us.r-project.org")
library(kableExtra)

```


```{r, echo=FALSE}

# Variables to modify
smallest_prime_to_consider <- 2
max_k <- 23 # Max k for which to find U_k
max_prime <- 200 # max prime to consider

```


```{r, echo=FALSE, warning=FALSE, include=FALSE}

# Add the R script containing the functions used here
source("functions.R")

```


```{r, echo=FALSE}

# Find U_k for each k in [1:max_k] and make a plot
# The values of U_k for k in [1,23] are saved in ./data. To read them: readRDS('data/up_to_u_23')
set_of_union_of_sets_of_lengths <- find_set_of_union_of_sets_of_lengths(max_k)

max_length <- length(set_of_union_of_sets_of_lengths[[length(set_of_union_of_sets_of_lengths)]])
fill_list <- function(my_list){
  diff_length <- max_length - length(my_list)
  return(c(my_list, rep(" ", diff_length)))
}
set_of_union_of_sets_of_lengths <- lapply(set_of_union_of_sets_of_lengths, fill_list)
set_of_union_of_sets_of_lengths <- as.data.frame(set_of_union_of_sets_of_lengths)
colnames(set_of_union_of_sets_of_lengths) <- c(paste0("U~", 1:max_k, "~"))
kable(set_of_union_of_sets_of_lengths) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

draw_plot(set_of_union_of_sets_of_lengths)

```

